version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: "0.0.0.0"
    ports:
      - 5674:5672
      - 4373:4369
      - 15674:15672
    tty: true
    stdin_open: true

  redis:
    image: redis:latest
    container_name: 'redis'
    hostname: "redis"
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/mime.types:/etc/nginx/mime.types
      - ./media:/data
    ports:
      - "8093:80"

  fastapi:
    build: .
    container_name: 'fastapi'
    ports:
      - "8094:8000"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - redis
    environment:
      - DEEZER_ARL=""
      - MEDIA_URL="http://192.168.0.83/media/"
      - REDIS_URL="redis://redis:6379/0"

  task_worker:
    build: .
    container_name: 'task_worker'
    command: python utils/task_worker/task_worker.py
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - redis
    environment:
      - DEEZER_ARL=""
      - MEDIA_URL="http://192.168.0.83/media/"
      - REDIS_URL="redis://redis:6379/0"