version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    tty: true
    stdin_open: true
    network_mode: host
    healthcheck:
      test: [ "CMD", "nc", "-z", "127.0.0.1", "5672" ]
      interval: 5s
      timeout: 50s
      retries: 10

  redis:
    image: redis:latest
    hostname: "redis"
    network_mode: host

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=
    depends_on:
      - fastapi
    network_mode: host
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./mime.types:/etc/nginx/mime.types
      - ../backend/media:/data

  fastapi:
    build: ../backend
    volumes:
      - ../backend:/code
    network_mode: host
    command: uvicorn main:app --host 0.0.0.0 --port 8062
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      upnp_listener:
        condition: service_started
    environment:
      - DEEZER_ARL=
      - MEDIA_URL=http://192.168.0.83:8063/media/
      - REDIS_URL=redis://localhost:6379/0
      - RABBITMQ_URL=amqp://guest:guest@localhost:5672/
      - PORT=8062
  task_worker:
    build: ../backend
    command: python /code/utils/task_worker/task_worker.py
    network_mode: host
    volumes:
      - ../backend:/code
    depends_on:
      rabbitmq:
        condition: service_healthy

      redis:
        condition: service_started
      upnp_listener:
        condition: service_started
    environment:
      - DEEZER_ARL=
      - MEDIA_URL=http://192.168.0.83:8063/media/
      - REDIS_URL=redis://localhost:6379/0
      - RABBITMQ_URL=amqp://guest:guest@localhost:5672/

  upnp_listener:
      build: ../backend
      command: python /code/utils/upnp_listener/producer.py
      network_mode: host
      depends_on:
        rabbitmq:
          condition: service_healthy

      volumes:
          - ../backend:/code
      environment:
        - DEEZER_ARL=
        - MEDIA_URL=http://192.168.0.83:8063/media/
        - REDIS_URL=redis://localhost:6379/0
        - RABBITMQ_URL=amqp://guest:guest@localhost:5672/