version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: "0.0.0.0"
    ports:
      - 5674:5672
      - 4373:4369
      - 15674:15672
    tty: true
    stdin_open: true

  redis:
    image: redis:latest
    container_name: 'redis'
    hostname: "redis"
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./mime.types:/etc/nginx/mime.types
      - ../backend/media:/data
    ports:
      - "8063:8063"
